# Generated by Django 5.2.13 on 2026-05-13 11:20

import django.db.models.deletion
import savings.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration_months', models.IntegerField(blank=True, null=True)),
                ('interest_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_flexible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SavingAccount',
            fields=[
                ('account_number', models.CharField(default=savings.models.generate_account_number, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('citizen_id', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interest_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_accounts', to=settings.AUTH_USER_MODEL)),
                ('saving_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='savings.savingtype')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('transaction_type', models.CharField(choices=[('OPEN', 'Account Opening'), ('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdrawal'), ('CLOSE', 'Account Closing')], max_length=10)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='savings.savingaccount')),
            ],
        ),
    ]
