# Generated by Django 6.0.5 on 2026-05-16 16:06

import django.db.models.deletion
from django.db import migrations, models
from django.utils.timezone import now


def backfill_rate_history_and_accrual_marker(apps, schema_editor):
    SavingType = apps.get_model("savings", "SavingType")
    SavingTypeRateHistory = apps.get_model("savings", "SavingTypeRateHistory")
    SavingAccount = apps.get_model("savings", "SavingAccount")

    today = now().date()

    # Seed one open history row for existing saving types.
    for st in SavingType.objects.all():
        SavingTypeRateHistory.objects.create(
            saving_type=st,
            interest_rate=st.interest_rate,
            effective_from=today,
            effective_to=None,
        )

    # Existing flexible accounts start accrual tracking from their start date.
    SavingAccount.objects.filter(
        saving_type__is_flexible=True,
        interest_last_applied_on__isnull=True,
    ).update(interest_last_applied_on=models.F("start_date"))


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingaccount',
            name='interest_last_applied_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SavingTypeRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('saving_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_history', to='savings.savingtype')),
            ],
            options={
                'ordering': ['effective_from'],
            },
        ),
        migrations.RunPython(backfill_rate_history_and_accrual_marker, migrations.RunPython.noop),
    ]
